-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- 1. Memory Bank Table
CREATE TABLE IF NOT EXISTS agent_memory_bank (
  id bigint generated by default as identity primary key,
  content text not null,
  memory_type text not null, -- 'FACT', 'EPISODE', 'INSIGHT', 'SOP'
  embedding vector(1536), -- Compatible with text-embedding-3-small
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

-- Index for Vector Search (HNSW)
CREATE INDEX IF NOT EXISTS idx_agent_memory_embedding 
ON agent_memory_bank USING hnsw (embedding vector_cosine_ops);


-- 2. RPC: Sales Trend Logic (Strict Tool)
-- Returns daily sales aggregate for a given period and optional keyword search on item name.
CREATE OR REPLACE FUNCTION op_sales_trend(
  p_start_date date,
  p_end_date date,
  p_keyword text default null
)
RETURNS TABLE (
  sale_date date,
  total_qty bigint,
  total_revenue numeric,
  top_item text
)
AS $$
BEGIN
  RETURN QUERY
  WITH DailyStats AS (
      SELECT
          sd.sale_date,
          SUM(sd.quantity) as qty,
          SUM(sd.revenue) as rev,
          -- Find top item for the day
          (SELECT x.item_name 
           FROM cms_sales_data x 
           WHERE x.sale_date = sd.sale_date 
             AND (p_keyword IS NULL OR x.item_name ILIKE '%' || p_keyword || '%')
           ORDER BY x.quantity DESC LIMIT 1) as top_item_name
      FROM cms_sales_data sd
      WHERE sd.sale_date BETWEEN p_start_date AND p_end_date
        AND (p_keyword IS NULL OR sd.item_name ILIKE '%' || p_keyword || '%')
      GROUP BY sd.sale_date
  )
  SELECT
      d.sale_date,
      d.qty::bigint,
      d.rev,
      d.top_item_name
  FROM DailyStats d
  ORDER BY d.sale_date;
END;
$$ LANGUAGE plpgsql;


-- 3. RPC: Inventory Check Logic (Strict Tool)
-- Checks current stock (bal_qty) from cm_erp_products
CREATE OR REPLACE FUNCTION op_inventory_check(
  p_keyword text
)
RETURNS TABLE (
  item_name text,
  current_stock integer,
  safety_stock integer
)
AS $$
BEGIN
  RETURN QUERY
  SELECT
      ep.item_name::text,
      COALESCE(ep.bal_qty, 0) as current_stock,
      100 as safety_stock -- Placeholder, ideally from DB
  FROM cm_erp_products ep
  WHERE ep.item_name ILIKE '%' || p_keyword || '%'
  ORDER BY ep.bal_qty DESC
  LIMIT 20;
END;
$$ LANGUAGE plpgsql;


-- 4. RPC: Promotion History Check (Strict Tool)
-- Checks past promotion performance
CREATE OR REPLACE FUNCTION op_promotion_history(
  p_keyword text
)
RETURNS TABLE (
  promo_name text,
  start_date date,
  end_date date,
  review_comment text
)
AS $$
BEGIN
  RETURN QUERY
  SELECT
      r.promo_name,
      r.start_date,
      r.end_date,
      r.review_comment
  FROM cm_promo_rules r
  WHERE (r.promo_name ILIKE '%' || p_keyword || '%')
     OR (r.review_comment ILIKE '%' || p_keyword || '%')
  ORDER BY r.start_date DESC
  LIMIT 10;
END;
$$ LANGUAGE plpgsql;


-- Grant access to authenticated users
GRANT SELECT, INSERT, UPDATE ON agent_memory_bank TO authenticated;
GRANT TEMPORARY ON DATABASE postgres TO authenticated; -- often needed for specialized functions
-- Grant execute on functions
GRANT EXECUTE ON FUNCTION op_sales_trend TO authenticated;
GRANT EXECUTE ON FUNCTION op_inventory_check TO authenticated;
GRANT EXECUTE ON FUNCTION op_promotion_history TO authenticated;
